# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9967a5c1f17d34c8a705ca073b1b1e1334981423a5fdacba424227bd1bbbc91a5fea9d9fbc504bf8c2f335fa12331cc7cb2d3c01e83901ef1d88ae23928a6e3d
  database:
    :username: "silkfred"
    :password: "justatest"
    :name: "silkfred_dev"
test:
  secret_key_base: b76d9a43208b1d72a759ec00222e19aacc6f237dd9557893df82b22523dce055a29c592e9bed6729a161440c4c4e271abeffd253af09d2a2ede331344b923123
  database:
    :username: "silkfred"
    :password: "justatest"
    :name: "silkfred_test"
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database:
    :username: "silkfred"
    :password: "justatest"
    :name: "silkfred_prod"
